/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.purdue.cs.pursec.ifuzzer.searchservice;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-08-29")
public class PathService {

  public interface Iface {

    public java.util.List<java.lang.String> findPaths(java.lang.String dpid, int egressPort, java.lang.String packetheader) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void findPaths(java.lang.String dpid, int egressPort, java.lang.String packetheader, org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public java.util.List<java.lang.String> findPaths(java.lang.String dpid, int egressPort, java.lang.String packetheader) throws org.apache.thrift.TException
    {
      send_findPaths(dpid, egressPort, packetheader);
      return recv_findPaths();
    }

    public void send_findPaths(java.lang.String dpid, int egressPort, java.lang.String packetheader) throws org.apache.thrift.TException
    {
      findPaths_args args = new findPaths_args();
      args.setDpid(dpid);
      args.setEgressPort(egressPort);
      args.setPacketheader(packetheader);
      sendBase("findPaths", args);
    }

    public java.util.List<java.lang.String> recv_findPaths() throws org.apache.thrift.TException
    {
      findPaths_result result = new findPaths_result();
      receiveBase(result, "findPaths");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "findPaths failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void findPaths(java.lang.String dpid, int egressPort, java.lang.String packetheader, org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      findPaths_call method_call = new findPaths_call(dpid, egressPort, packetheader, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class findPaths_call extends org.apache.thrift.async.TAsyncMethodCall<java.util.List<java.lang.String>> {
      private java.lang.String dpid;
      private int egressPort;
      private java.lang.String packetheader;
      public findPaths_call(java.lang.String dpid, int egressPort, java.lang.String packetheader, org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.dpid = dpid;
        this.egressPort = egressPort;
        this.packetheader = packetheader;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("findPaths", org.apache.thrift.protocol.TMessageType.CALL, 0));
        findPaths_args args = new findPaths_args();
        args.setDpid(dpid);
        args.setEgressPort(egressPort);
        args.setPacketheader(packetheader);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public java.util.List<java.lang.String> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_findPaths();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("findPaths", new findPaths());
      return processMap;
    }

    public static class findPaths<I extends Iface> extends org.apache.thrift.ProcessFunction<I, findPaths_args> {
      public findPaths() {
        super("findPaths");
      }

      public findPaths_args getEmptyArgsInstance() {
        return new findPaths_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public findPaths_result getResult(I iface, findPaths_args args) throws org.apache.thrift.TException {
        findPaths_result result = new findPaths_result();
        result.success = iface.findPaths(args.dpid, args.egressPort, args.packetheader);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("findPaths", new findPaths());
      return processMap;
    }

    public static class findPaths<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, findPaths_args, java.util.List<java.lang.String>> {
      public findPaths() {
        super("findPaths");
      }

      public findPaths_args getEmptyArgsInstance() {
        return new findPaths_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>>() { 
          public void onComplete(java.util.List<java.lang.String> o) {
            findPaths_result result = new findPaths_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            findPaths_result result = new findPaths_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, findPaths_args args, org.apache.thrift.async.AsyncMethodCallback<java.util.List<java.lang.String>> resultHandler) throws org.apache.thrift.TException {
        iface.findPaths(args.dpid, args.egressPort, args.packetheader,resultHandler);
      }
    }

  }

  public static class findPaths_args implements org.apache.thrift.TBase<findPaths_args, findPaths_args._Fields>, java.io.Serializable, Cloneable, Comparable<findPaths_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("findPaths_args");

    private static final org.apache.thrift.protocol.TField DPID_FIELD_DESC = new org.apache.thrift.protocol.TField("dpid", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField EGRESS_PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("egressPort", org.apache.thrift.protocol.TType.I32, (short)2);
    private static final org.apache.thrift.protocol.TField PACKETHEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("packetheader", org.apache.thrift.protocol.TType.STRING, (short)3);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new findPaths_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new findPaths_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.lang.String dpid; // required
    public int egressPort; // required
    public @org.apache.thrift.annotation.Nullable java.lang.String packetheader; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      DPID((short)1, "dpid"),
      EGRESS_PORT((short)2, "egressPort"),
      PACKETHEADER((short)3, "packetheader");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // DPID
            return DPID;
          case 2: // EGRESS_PORT
            return EGRESS_PORT;
          case 3: // PACKETHEADER
            return PACKETHEADER;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __EGRESSPORT_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.DPID, new org.apache.thrift.meta_data.FieldMetaData("dpid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.EGRESS_PORT, new org.apache.thrift.meta_data.FieldMetaData("egressPort", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32          , "int")));
      tmpMap.put(_Fields.PACKETHEADER, new org.apache.thrift.meta_data.FieldMetaData("packetheader", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(findPaths_args.class, metaDataMap);
    }

    public findPaths_args() {
    }

    public findPaths_args(
      java.lang.String dpid,
      int egressPort,
      java.lang.String packetheader)
    {
      this();
      this.dpid = dpid;
      this.egressPort = egressPort;
      setEgressPortIsSet(true);
      this.packetheader = packetheader;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public findPaths_args(findPaths_args other) {
      __isset_bitfield = other.__isset_bitfield;
      if (other.isSetDpid()) {
        this.dpid = other.dpid;
      }
      this.egressPort = other.egressPort;
      if (other.isSetPacketheader()) {
        this.packetheader = other.packetheader;
      }
    }

    public findPaths_args deepCopy() {
      return new findPaths_args(this);
    }

    @Override
    public void clear() {
      this.dpid = null;
      setEgressPortIsSet(false);
      this.egressPort = 0;
      this.packetheader = null;
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getDpid() {
      return this.dpid;
    }

    public findPaths_args setDpid(@org.apache.thrift.annotation.Nullable java.lang.String dpid) {
      this.dpid = dpid;
      return this;
    }

    public void unsetDpid() {
      this.dpid = null;
    }

    /** Returns true if field dpid is set (has been assigned a value) and false otherwise */
    public boolean isSetDpid() {
      return this.dpid != null;
    }

    public void setDpidIsSet(boolean value) {
      if (!value) {
        this.dpid = null;
      }
    }

    public int getEgressPort() {
      return this.egressPort;
    }

    public findPaths_args setEgressPort(int egressPort) {
      this.egressPort = egressPort;
      setEgressPortIsSet(true);
      return this;
    }

    public void unsetEgressPort() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EGRESSPORT_ISSET_ID);
    }

    /** Returns true if field egressPort is set (has been assigned a value) and false otherwise */
    public boolean isSetEgressPort() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EGRESSPORT_ISSET_ID);
    }

    public void setEgressPortIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EGRESSPORT_ISSET_ID, value);
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getPacketheader() {
      return this.packetheader;
    }

    public findPaths_args setPacketheader(@org.apache.thrift.annotation.Nullable java.lang.String packetheader) {
      this.packetheader = packetheader;
      return this;
    }

    public void unsetPacketheader() {
      this.packetheader = null;
    }

    /** Returns true if field packetheader is set (has been assigned a value) and false otherwise */
    public boolean isSetPacketheader() {
      return this.packetheader != null;
    }

    public void setPacketheaderIsSet(boolean value) {
      if (!value) {
        this.packetheader = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case DPID:
        if (value == null) {
          unsetDpid();
        } else {
          setDpid((java.lang.String)value);
        }
        break;

      case EGRESS_PORT:
        if (value == null) {
          unsetEgressPort();
        } else {
          setEgressPort((java.lang.Integer)value);
        }
        break;

      case PACKETHEADER:
        if (value == null) {
          unsetPacketheader();
        } else {
          setPacketheader((java.lang.String)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case DPID:
        return getDpid();

      case EGRESS_PORT:
        return getEgressPort();

      case PACKETHEADER:
        return getPacketheader();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case DPID:
        return isSetDpid();
      case EGRESS_PORT:
        return isSetEgressPort();
      case PACKETHEADER:
        return isSetPacketheader();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that instanceof findPaths_args)
        return this.equals((findPaths_args)that);
      return false;
    }

    public boolean equals(findPaths_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_dpid = true && this.isSetDpid();
      boolean that_present_dpid = true && that.isSetDpid();
      if (this_present_dpid || that_present_dpid) {
        if (!(this_present_dpid && that_present_dpid))
          return false;
        if (!this.dpid.equals(that.dpid))
          return false;
      }

      boolean this_present_egressPort = true;
      boolean that_present_egressPort = true;
      if (this_present_egressPort || that_present_egressPort) {
        if (!(this_present_egressPort && that_present_egressPort))
          return false;
        if (this.egressPort != that.egressPort)
          return false;
      }

      boolean this_present_packetheader = true && this.isSetPacketheader();
      boolean that_present_packetheader = true && that.isSetPacketheader();
      if (this_present_packetheader || that_present_packetheader) {
        if (!(this_present_packetheader && that_present_packetheader))
          return false;
        if (!this.packetheader.equals(that.packetheader))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetDpid()) ? 131071 : 524287);
      if (isSetDpid())
        hashCode = hashCode * 8191 + dpid.hashCode();

      hashCode = hashCode * 8191 + egressPort;

      hashCode = hashCode * 8191 + ((isSetPacketheader()) ? 131071 : 524287);
      if (isSetPacketheader())
        hashCode = hashCode * 8191 + packetheader.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(findPaths_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.compare(isSetDpid(), other.isSetDpid());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetDpid()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dpid, other.dpid);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.compare(isSetEgressPort(), other.isSetEgressPort());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetEgressPort()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.egressPort, other.egressPort);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.compare(isSetPacketheader(), other.isSetPacketheader());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetPacketheader()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.packetheader, other.packetheader);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("findPaths_args(");
      boolean first = true;

      sb.append("dpid:");
      if (this.dpid == null) {
        sb.append("null");
      } else {
        sb.append(this.dpid);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("egressPort:");
      sb.append(this.egressPort);
      first = false;
      if (!first) sb.append(", ");
      sb.append("packetheader:");
      if (this.packetheader == null) {
        sb.append("null");
      } else {
        sb.append(this.packetheader);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class findPaths_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public findPaths_argsStandardScheme getScheme() {
        return new findPaths_argsStandardScheme();
      }
    }

    private static class findPaths_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<findPaths_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, findPaths_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // DPID
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.dpid = iprot.readString();
                struct.setDpidIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // EGRESS_PORT
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.egressPort = iprot.readI32();
                struct.setEgressPortIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // PACKETHEADER
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.packetheader = iprot.readString();
                struct.setPacketheaderIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, findPaths_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.dpid != null) {
          oprot.writeFieldBegin(DPID_FIELD_DESC);
          oprot.writeString(struct.dpid);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldBegin(EGRESS_PORT_FIELD_DESC);
        oprot.writeI32(struct.egressPort);
        oprot.writeFieldEnd();
        if (struct.packetheader != null) {
          oprot.writeFieldBegin(PACKETHEADER_FIELD_DESC);
          oprot.writeString(struct.packetheader);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class findPaths_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public findPaths_argsTupleScheme getScheme() {
        return new findPaths_argsTupleScheme();
      }
    }

    private static class findPaths_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<findPaths_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, findPaths_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetDpid()) {
          optionals.set(0);
        }
        if (struct.isSetEgressPort()) {
          optionals.set(1);
        }
        if (struct.isSetPacketheader()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetDpid()) {
          oprot.writeString(struct.dpid);
        }
        if (struct.isSetEgressPort()) {
          oprot.writeI32(struct.egressPort);
        }
        if (struct.isSetPacketheader()) {
          oprot.writeString(struct.packetheader);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, findPaths_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.dpid = iprot.readString();
          struct.setDpidIsSet(true);
        }
        if (incoming.get(1)) {
          struct.egressPort = iprot.readI32();
          struct.setEgressPortIsSet(true);
        }
        if (incoming.get(2)) {
          struct.packetheader = iprot.readString();
          struct.setPacketheaderIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class findPaths_result implements org.apache.thrift.TBase<findPaths_result, findPaths_result._Fields>, java.io.Serializable, Cloneable, Comparable<findPaths_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("findPaths_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new findPaths_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new findPaths_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(findPaths_result.class, metaDataMap);
    }

    public findPaths_result() {
    }

    public findPaths_result(
      java.util.List<java.lang.String> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public findPaths_result(findPaths_result other) {
      if (other.isSetSuccess()) {
        java.util.List<java.lang.String> __this__success = new java.util.ArrayList<java.lang.String>(other.success);
        this.success = __this__success;
      }
    }

    public findPaths_result deepCopy() {
      return new findPaths_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Iterator<java.lang.String> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(java.lang.String elem) {
      if (this.success == null) {
        this.success = new java.util.ArrayList<java.lang.String>();
      }
      this.success.add(elem);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.List<java.lang.String> getSuccess() {
      return this.success;
    }

    public findPaths_result setSuccess(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((java.util.List<java.lang.String>)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that instanceof findPaths_result)
        return this.equals((findPaths_result)that);
      return false;
    }

    public boolean equals(findPaths_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(findPaths_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.compare(isSetSuccess(), other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("findPaths_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class findPaths_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public findPaths_resultStandardScheme getScheme() {
        return new findPaths_resultStandardScheme();
      }
    }

    private static class findPaths_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<findPaths_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, findPaths_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.success = new java.util.ArrayList<java.lang.String>(_list0.size);
                  @org.apache.thrift.annotation.Nullable java.lang.String _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = iprot.readString();
                    struct.success.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, findPaths_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.success.size()));
            for (java.lang.String _iter3 : struct.success)
            {
              oprot.writeString(_iter3);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class findPaths_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public findPaths_resultTupleScheme getScheme() {
        return new findPaths_resultTupleScheme();
      }
    }

    private static class findPaths_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<findPaths_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, findPaths_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (java.lang.String _iter4 : struct.success)
            {
              oprot.writeString(_iter4);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, findPaths_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
            struct.success = new java.util.ArrayList<java.lang.String>(_list5.size);
            @org.apache.thrift.annotation.Nullable java.lang.String _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = iprot.readString();
              struct.success.add(_elem6);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
